FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Ho_Chi_Minh

# Install PHP, Apache, and Composer dependencies
RUN apt-get update && \
    apt-get install -y \
        apache2 \
        php \
        libapache2-mod-php \
        php-mysql \
        php-xml \
        unzip \
        curl \
        git \
        php-cli \
        php-mbstring \
        php-zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Enable Apache rewrite module
RUN a2enmod rewrite

# Copy Composer from official image
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer
RUN composer config --global process-timeout 1200

# Expose Apache port
EXPOSE 80

# Default command
CMD ["apachectl", "-D", "FOREGROUND"]
